### PR TITLE
Add troubleshooting section.

### PR DESCRIPTION
**Pull request by Ipreaw**
add troubleshooting for changing sandbox mode for issue #9 .

### CODE REVIEW

**Comment by calonso** [comment]
Hey @Ipreaw this is great!!

A couple of comments. I think it will be easier to search if the title of the entry (Currently don't forget to...) is actually the error, as the potential affected user will be looking for something like: If you see `255 Unknown Error` error codes... and then the error explanation and solution.

On the other hand, the code shouldn't crash with the `NoMethodError`. For some reason, when pushing multiple notifications with this bad configuration, it gets [here](https://github.com/calonso/ruby-push-notifications/blob/master/lib/ruby-push-notifications/apns/apns_pusher.rb#L55) with a value of `i` bigger than 0, leading to the crash. The expected output in this case should be to have all response codes with `255 Unknown Error`.

Does it make sense? Would you like to investigate why as well?

Thanks!

**Comment by calonso** [comment]
That's great.

Are you investigating why it crashes instead of successfully returning a 255 error code for each notification?

**Comment by calonso** [comment]
Hi @Ipreaw 
Are you planning on debugging further to avoid the crash and return a `255` error code for each notification instead? 
Do you need any help or you prefer me to merge this PR as is?

Regards

**Comment by Ipreaw** [comment]
@calonso Sorry for that I can't find how to avoid the crash. That is so great if you help me.

**Pull request merged**
