### PR TITLE
fixed SSLv3 version

### PR DESCRIPTION
**Pull request by dmkl**
Fix for APN connection failing with message `SSL_connect SYSCALL returned=5 errno=0 state=SSLv3 read server session ticket A`

### CODE REVIEW

**Comment by calonso** [comment]
@dmkl This looks good, except for the fact that Ruby 1.9.3 seems to not accept the new argument (see travis failed job).

Can you fix it before merging?

I'd also like to know what is this exactly changing and which are the implications.

Cheers!

**Comment by dmkl** [comment]
@calonso yes, sorry, I opened a PR too early. I will fix it for my project first and update it then. Let's close it for now.

There is a weird problem with SSL. Not all, but many pushes fail with `SSL_connect SYSCALL returned=5 errno=0 state=SSLv3 read server session ticket A` error message.

**Comment by calonso** [comment]
@dmkl According to this thread(https://github.com/grocer/grocer/issues/88), it can also be that your certificate is expired, but testing different security mechanisms to see which ones work sounds interesting.
The thread says that TLSv1 is the only supported in both production and sandbox, could you confirm that?

**Comment by dmkl** [comment]
@calonso it seems that TLSv1 doesn't fix my problem, request still fails with the same `SSL_connect SYSCALL returned=5 errno=0 state=SSLv3 read server session ticket A`. I will close this PR for now.

**Pull request closed without merging**
