### PR TITLE
Add intermediate module definitions

### PR DESCRIPTION
**Pull request by sobakasu**
I was getting the error 'uninitialized constant RubyPushNotifications::FCM'. these changes seem to fix that. Not sure if it's a ruby 2.5.5 idiosyncrasy

> irb(main):004:0> RubyPushNotifications::FCM::FCMPusher
> Traceback (most recent call last):
>         1: from (irb):4
> NameError (uninitialized constant RubyPushNotifications::FCM)

### CODE REVIEW

**Comment by Juksefantomet** [comment]
@sobakasu 

Just checking here, did you build the gem and install it manually? As the FCM implementation has not been released in any gem version yet as far as i can see?

I was getting that when i forgot to uninstall the ruby-push-notifications gem and manually build from the repo when i was implementing these changes :smile:

**Comment by Juksefantomet** [comment]
please try these steps first just to confirm:

gem uninstall ruby-push-notifications
mkdir test
cd test
git clone this_repo
cd ruby-push-notifications
gem build ruby-push-notifications.gemspec
gem install ruby-push-notifications-x.x.x

irb
require 'ruby-push-notifications-
run your failing command again

**Comment by Magnus9** [comment]
> please try these steps first just to confirm:
> 
> gem uninstall ruby-push-notifications
> mkdir test
> cd test
> git clone this_repo
> cd ruby-push-notifications
> gem build ruby-push-notifications.gemspec
> gem install ruby-push-notifications-x.x.x
> 
> irb
> require 'ruby-push-notifications-
> run your failing command again

I can confirm this, this worked for me

**Comment by sobakasu** [comment]
if the FCM implementation hasn't been released in a gem that explains why I was getting this error :)
disregard this pull request then!

**Comment by Juksefantomet** [comment]
@sobakasu no problem at all, i am making an issue post to counter any future misunderstandings until it is released by @calonso 

Thank you for the pull request though, any improvements are always appreciated!

**Comment by Juksefantomet** [comment]
@sobakasu The gem is now officially bumped!

**Pull request closed without merging**
